### ISSUE TITLE
Harmonize colors on the dashboard

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#186]
Steps:

0) Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md).
1) Check out the current implementation of our streamlit dashboard: [https://github.com/CarmineOptions/derisk-research/blob/master/app.py](https://github.com/CarmineOptions/derisk-research/blob/master/app.py). The dashboard can be found [here](https://starknet.derisk.carmine.finance/).
2) The dashboard displays various components, the colors of which are not aligned, which is distracting, and makes the dashboard less readable/understandable. Check e.g. these examples:
![image](https://github.com/user-attachments/assets/d4a7e320-cb8b-429d-a49c-76971cdb9196)
![image](https://github.com/user-attachments/assets/866bfc07-b375-4b2c-9544-67b4f47114da)
![image](https://github.com/user-attachments/assets/072a7f8b-073c-454e-a401-441fb4519779)
3) Harmonize the colors and keep in mind that the user should be able to distinguish between
a) supply and demand in the main chart by their color, and
b) individual lending protocols by their color (note that in the pie charts, the colors are distributed by the rank of the protocol, hence, e.g., Nostra Mainnet is not always dark blue in the supply charts, which is wrong and should be fixed), and
c) deposit, collateral, or debt by their color.

**Comment by ShantelPeters** [comment]
Hi

**Comment by martinvibes** [comment]
d

**Comment by dev-chinx** [comment]
hello @lukaspetrasek i am a frontend dev and blockchain developer
please can i work on this issue :) and i would love to be a contributor as it is my first time contributing

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hi I would love to work on this issue

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged

Hello, i am Dprof-in-tech, an experienced Full Stack Blockchain Developer and  I am excited to contribute my skills to this project in this ODHACK 8. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js, Rust and Cairo, I've honed my technical skills across the blockchain development landscape.
My journey with OnlyDust began at Edition 2, and I've since made 34 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines. I bring a unique blend of technical prowess and user-centric design to every project, whether I'm crafting immersive 3D experiences or developing innovative smart contracts.
My track record demonstrates my ability to adapt quickly and contribute effectively to diverse challenges. I'm confident in my capacity to tackle new problems and drive innovation in the blockchain space. As we begin ODHACK 8, I'm eager to leverage my hackathon experience and technical skills to push the boundaries of what's possible in blockchain development.
Below is a link to my OnlyDust public profile.
https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Approach for Harmonize Colors on the Dashboard (#186):
I will read and understand the current setup:
I will start by reviewing the Contributor Guidelines and README to ensure I follow the project standards and best practices for UI/UX and code consistency.
Then, I will study the current implementation of the Streamlit dashboard located in app.py and its styling logic. This will help me understand how the colors are currently applied across various components, including the main chart, pie charts, and other sections of the dashboard.
I will identify color inconsistencies:
I will run the dashboard locally to visually inspect the color schemes used in different components, such as the main chart (for supply and demand) and the pie charts (for lending protocols).
I will pinpoint specific areas where colors are inconsistent or unclear, such as supply vs. demand, deposit vs. collateral vs. debt, and lending protocols' rank-based color distribution (e.g., Nostra Mainnet not consistently using dark blue in the pie charts).
I will document all the identified color issues that reduce readability and clarity for users.
I will research and define a consistent color scheme:
I will choose a color palette that aligns with the project's existing style guide while also enhancing the dashboard's usability. This palette will include distinct, non-conflicting colors for:
Supply and demand in the main chart (ensuring users can easily distinguish between them).
Individual lending protocols, where colors should remain consistent across charts (e.g., Nostra Mainnet always being represented by dark blue).
Deposit, collateral, and debt, ensuring these roles are clearly differentiated by color to avoid user confusion.
I will ensure the selected colors are easy on the eyes and promote readability in both light and dark modes, keeping accessibility in mind (e.g., color contrast for visually impaired users).
I will harmonize and apply the new color scheme:
I will update the existing color definitions in the code to apply the new harmonized color scheme across all relevant components:
The main chart will be updated to clearly distinguish between supply and demand.
The pie charts will be fixed so that each lending protocol consistently retains its assigned color (e.g., Nostra Mainnet is always dark blue).
Colors will be applied systematically across deposit, collateral, and debt sections, ensuring clarity for users when switching between these views.
I will test the color scheme in both light and dark modes to ensure that it remains visually appealing and functional across different themes.
I will ensure the changes are responsive and test thoroughly:
I will verify that the new color scheme remains consistent and readable on various screen sizes and resolutions. This is crucial since users may access the dashboard from different devices.
I will test the dashboard across multiple browsers and screen sizes to ensure the color harmony holds up across all environments.
I will gather feedback and iterate if necessary:
Before submitting the final solution, I will share the updated color scheme and changes with the team (or stakeholders) to gather feedback. If any suggestions for improvement arise, I will make the necessary adjustments.
I will document the changes:
I will update the documentation to reflect the new color scheme rules and how they are applied throughout the dashboard.
I will include guidance on how future updates to colors should follow the newly established scheme for consistency.
Estimated Timeline:
Start Date: Immediately upon assignment.
Estimated Completion Date: 2 days from the start date (ETA: 2 days).
By implementing this solution, I will ensure that the dashboard's colors are harmonized and consistent, improving the user experience and making the data easier to understand at a glance.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
 

I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will start by analyzing the current color scheme in the Streamlit dashboard, identifying inconsistencies across different components. I will create a color palette that allows clear distinction between supply and demand, individual lending protocols, and deposit/collateral/debt categories. I will use a consistent color mapping for each lending protocol across all charts, ensuring Nostra Mainnet always appears in dark blue, for example. I will modify the code to use this consistent color scheme, particularly focusing on the pie charts where colors are currently distributed by protocol rank. I will implement a custom color function that assigns colors based on protocol identity rather than rank. I will ensure that the main chart clearly differentiates between supply and demand using contrasting colors. I will test the new color scheme across various data scenarios to confirm readability and understanding are improved. Finally, I will update any legend or key to reflect the new, harmonized color scheme

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
Hello @lukaspetrasek I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute

### How I plan on tackling this issue
To solve this issue i will ensure that the  colors on the dashboard are harmonized. As a frontend developer I will be able to complete this in 2-3 days

**Comment by lukaspetrasek** [comment]
Hi everyone, assigning @martinvibes!

@martinvibes Let me know if everything is clear. If you have any questions, please ask here. What is you TG handler please? 🙏🏼 

Consider joining our [TG group](https://t.me/derisk_dev).
See also our [contributor guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md).

**Comment by djeck1432** [comment]
Hi @martinvibes  any progress, if you need any help, just let me know

**Comment by martinvibes** [comment]
@djeck1432 I will make a pr soon

**Comment by djeck1432** [comment]
> @djeck1432 I will make a pr soon

Great, please, assign me as a code reviewer,
Thank you

**Comment by djeck1432** [comment]
Hi @martinvibes you have 24 hours to open draft PR otherwise this issue will be assigned to another user.
