### ISSUE TITLE
Refactor EkuboLiquidity for better readability and maintenance

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#198]
## Task Description

Refactor [add_ekubo_liquidity()](https://github.com/CarmineOptions/derisk-research/blob/master/app.py#L48) function by creating a new class EkuboLiquidity. This will improve the code’s readability and maintainability.

## Steps

1. Review our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md)

2. Set up the project and create a new branch:
   • Fork this repository.
   • Create a new branch for your work.

3. Install the project [installation guide](https://gist.github.com/djeck1432/cd3ea7ecc0f71b44ec4db5b1f30c4574)
4. Create a new file `utils.py` in the root folder.
5. In utils.py, create a class `EkuboLiquidity` with the following structure:
	Class variables:
	• URL = "http://178.32.172.153/orderbook/"
	• DEX = 'Ekubo'
	Methods:
	• `__init__(self, data, collateral_token, debt_token)`
Initializes the class with provided data, collateral token, and debt token.
	• `apply_liquidity_to_dataframe(self, bids_or_asks)`
Applies liquidity data to a dataframe.
	• `fetch_liquidity(self)`
Fetches liquidity data from the endpoint.
	• `_get_available_liquidity(self)`
6. Refer to the [add_ekubo_liquidity()](https://github.com/CarmineOptions/derisk-research/blob/master/app.py#L48)  function in app.py for additional context and logic to help with the implementation.
7. Substitute `add_ekubo_liquidity()` with `EkuboLiquidity` class in [main()](https://github.com/CarmineOptions/derisk-research/blob/master/app.py#L199) function in `app.py`

**Comment by ShantelPeters** [comment]
Hi

**Comment by od-hunter** [comment]
Hi can I work on this please @djeck1432

**Comment by vitaliypopel** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I'm python developer

### How I plan on tackling this issue
To solve this issue, I would approach it as follows:

 1. Create the Class Structure: I will start by creating the EkuboLiquidity class in the utils.py file. I’ll define the class variables URL and DEX as constants at the top, since they are static and will be used throughout the class.
 2. Implement the Constructor: In the __init__ method, I’ll initialize the class with the required parameters: data, collateral_token, and debt_token. These will likely be stored as instance variables since they’ll be used by other methods in the class.
 3. Refactor Existing Functions:
 • apply_liquidity_to_dataframe: This method will take liquidity data (bids or asks) and process it into a Pandas dataframe for further analysis or usage.
 • fetch_liquidity: I’ll implement this method to fetch liquidity data from the given URL. This will involve making an HTTP request to the API endpoint, retrieving the JSON data, and returning it in a structured form.
 4. Migrate Helper Methods: The _get_available_liquidity method will be copied from the existing app.py. This method will stay private, as indicated by the underscore, and will assist the other public methods by providing preprocessed liquidity data.

**Comment by djeck1432** [comment]
Hi @ShantelPeters and @od-hunter, thanks for your interest! Just a quick note: you should apply via the OnlyDust platform rather than GitHub, as that’s the required process. It helps us stay aligned with OnlyDust’s guidelines. Let’s stick to this standard moving forward. Thanks for understanding! 😊

**Comment by od-hunter** [comment]
> Hi @ShantelPeters and @od-hunter, thanks for your interest! Just a quick note: you should apply via the OnlyDust platform rather than GitHub, as that’s the required process. It helps us stay aligned with OnlyDust’s guidelines. Let’s stick to this standard moving forward. Thanks for understanding! 😊

I applied via Onlydust ser

**Comment by ShantelPeters** [comment]
> Hi @ShantelPeters and @od-hunter, thanks for your interest! Just a quick note: you should apply via the OnlyDust platform rather than GitHub, as that’s the required process. It helps us stay aligned with OnlyDust’s guidelines. Let’s stick to this standard moving forward. Thanks for understanding! 😊

I  already applied via the onlydust plat

**Comment by djeck1432** [comment]
It's weird, once I have created this issue, I saw two first messages like:
1. Hi, Can I take this one
2. Hi, I have already finished my task, could you please assign me to this one.
Maybe some bug or freeze on OnlyDust side. Because OnlyDust message has own template which you can see above.

**Comment by jaykayudo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I am a python developer with ample experience in builidng software applications in several fields including  web3. I am an expert in code modularization which i believe make me a good pick for this task

### How I plan on tackling this issue
- I will follow the contribution guidelines for the project
- I will install the project dependencies on my  local device by folllowing the installation guide
- i will create the new file `utils.py` as proposed.
- I will create a class in the new file and extract the logics from the `app.py` `add_ekubo_liquidity()` and create a class methods for each of  the logics as proposed above.
- I will replace the `add_ekubo_liquidity()` with the newly created class as proposed.
- I will make sure the class  and its methods follows properly formatting syntax as the enable better readability
-  I will also make sure that it follows properly typing system to provide better understanding of the methods during future code maintenance
- I will test to make sure no code breakage was done during the modularization.
