### ISSUE TITLE
Split into modules chart code

### ISSUE THREAD

**Issue by djeck1432** [CarmineOptions/derisk-research#199]
## Task Description

The `main()` function in [app.py](http://app.py/) is currently too large, making it difficult to read and maintain. The goal of this task is to refactor the function by splitting it into smaller, more logical parts.

## Steps

1. Review our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md)

2. Set up the project and create a new branch:
    •Fork this repository.
   • Create a new branch for your work.

3. Install the project [installation guide](https://gist.github.com/djeck1432/cd3ea7ecc0f71b44ec4db5b1f30c4574)
4. Create a new file [charts.py](http://charts.py/) in the root folder.
5. In [charts.py](http://charts.py/), create functions to handle the following chart-related parts of `main()` from [app.py](http://app.py/)
  - [Comparison of lending protocols](https://github.com/CarmineOptions/derisk-research/blob/master/app.py#L436)
  - [Loans with low health factor](https://github.com/CarmineOptions/derisk-research/blob/master/app.py#L357)
  - [Top loans](https://github.com/CarmineOptions/derisk-research/blob/master/app.py#L374)
  - [Detail of a loan](https://github.com/CarmineOptions/derisk-research/blob/master/app.py#L393)

**Comment by UzNaZ** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I'm python Backend developer with experience in Web3 and blockchain.
1. I will review codebase
2. Follow the task description will do refactoring the code in `main()` function

### How I plan on tackling this issue
1. Understand the Existing Code: I would first thoroughly review the main() function in app.py, focusing on the sections related to chart generation. This will help in understanding the logic and how the different chart types are handled.
 2. Create charts.py File: I will create a new file, charts.py, in the root directory to organize the chart-related functionality into separate, cohesive functions.
 3. Refactor the Functionality:
 • Comparison of Lending Protocols: I’ll extract this part of the logic from main() and place it into a new function in charts.py. This function will handle all data processing and chart generation specific to comparing lending protocols.
 • Loans with Low Health Factor: Similarly, I’ll extract the logic for generating charts that show loans with a low health factor and place it in a dedicated function.
 • Top Loans: I will create another function to handle the generation of top loan charts, following the same process.
 • Detail of a Loan: Finally, I’ll extract the logic for generating detailed loan charts and move it into a separate function.
 4. Minimize Redundancy: I will look for common operations across these chart functions (e.g., data processing steps, chart formatting) and abstract them into helper functions to avoid code duplication.
 5. Testing: Once refactored, I’ll ensure that each function in charts.py works as expected by testing it individually and validating the output charts against the current functionality.
 6. Update main(): I will modify the main() function in app.py to call the appropriate functions from charts.py rather than directly handling the chart logic. This will make the main() function more readable and maintainable by reducing its complexity.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
hello i would love to take on this issue Please kindly assign

### How I plan on tackling this issue
Steps:

Review Contributor Guidelines and README.
Fork the repository and create a new branch.
Follow the installation guide to set up the project.
Create charts.py and implement functions for:
Comparison of lending protocols
Loans with low health factor
Top loans
Loan details

**Comment by jaykayudo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/derisk).

### My background and how it can be leveraged
I am a python developer with ample experience in builidng software applications in several fields including  web3. I am an expert in code modularization which i believe make me a good pick for this task

### How I plan on tackling this issue
- I will follow the project’s installation guide to set up the development environment, ensuring all dependencies are properly configured.
- I will create the `charts.py` file in the root directory and extract the logics for `comparison of lending protocols`, `loans with low health folder`, `top loans` and `detail of a loan` and create a function for each of this logics in the `charts.py` file while following good formatting and typing syntax.
- I will remove the chunks of codes in the `app.py` file `main` function and replace it  with the functions created in the `charts.py` file.
- I will test to make sure no code breakage was done during the modularization.
