### ISSUE TITLE
Setup a service which notifies users about their loans getting closer to liquidations

### ISSUE THREAD

**Issue by lukaspetrasek** [CarmineOptions/derisk-research#64]
Imagine a scenario where a user borrows 2000 USDC against 1 ETH at one of the lending protocols. At that point, the user's health ratio is far above 1, but the user risks being liquidated when it falls below 1. Because the user doesn't have time to check her health ratio frequently, she could subscribe to the service and get notified whenever the health ratio falls to predefined levels.

The user would provide the following information:
- Starknet wallet address
- Email address
- Health ratio levels

The service will monitor all loans taken under the wallet address supplied by the user and send notifications to the email address supplied by the user. The notifications will be sent whenever the health ratio falls below any supplied health ratio levels, provided the health ratio was above that level before.

**Comment by MarekHauzr** [comment]
@lukaspetrasek 
few notes:

Not one, but multiple STRK addresses

Input on which protocol the loan(s) are

on the backend it should allow for multiple submissions (ie not overwrite, but add to the previous submissions and keep the protocol ID)

there is a cap on how many emails we send per day per heath threshold crossing
- health goes up and below threshold many time in a day -> only one email was sent
- health went below one threshold -> email sent... then below another -> another email sent right away

Node that will be used for requesting the data should be configurable - so that it is possible to use private one.
